<?php
/**
 * Created by PhpStorm.
 * User: kshit
 * Date: 2019-05-13
 * Time: 11:42:29
 */

class Login_m extends MY_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function hash($string)
    {
        return parent::hash($string); // TODO: Change the autogenerated stub
    }
    // function check_user($username,$password,$otp)
    // {
    //     // $password = "Admin@123";
    //     $password = $this->hash($password);
      
      
    //     $check = $this->db->get_where('admin',array('username'=>$username,'password'=>$password,'otp'=>$otp))->row();
     
    //     if (!empty($check)){
    //         $this->set_session($check);
    //         return true;
    //     }else{
    //         return false;
    //     }
    // }
    function check_user($username,$password)
    {
        // $password = "Admin@123";
        $password = $this->hash($password);
      
      
        $check = $this->db->get_where('admin',array('username'=>$username,'password'=>$password))->row();
     
        if (!empty($check)){
            $this->set_session($check);
            return true;
        }else{
            return false;
        }
    }

    function set_session($login)
    {
        $data = array(
            "panel" => 'eazy_to_m_admin',
            "adminID" => $login->id,
            "name" => $login->name,
            "username" => $login->username,
            "email" => $login->email,
            "mobile" => $login->mobile,
            "image" =>$login->photo,
            "role" => $login->role,
            "loggedin" => TRUE,
            "cityID" => $login->city_id,
            "created_at" =>$login->created_at
        );    
        $this->session->set_userdata($data);
    }
}